name: geo_hash
description: A simple geohashing library for dart
version: 0.2.1
author: Adam Stark <llamadonica@gmail.com> [adapted by Raphael Smith <raphael@bmec.co>]
homepage: https://github.com/llamadonica/dart-geohash [https://github.com/BMEC/dart-geohash]

environment:
  sdk: '>=2.0.0-dev.69.5 <3.0.0'

dev_dependencies:
  test: ^1.2.0